// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3DrEGJqyDWRDtnNBEkBfDsxAOQ4zjD08',
    appId: '1:641698702113:web:727429f7db9b02d0709460',
    messagingSenderId: '641698702113',
    projectId: 'getx-student',
    authDomain: 'getx-student.firebaseapp.com',
    storageBucket: 'getx-student.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkwIiGTrSyJ1bd5M_RiNqYqAKelqa8b9o',
    appId: '1:641698702113:android:72d6a98dad18b84f709460',
    messagingSenderId: '641698702113',
    projectId: 'getx-student',
    storageBucket: 'getx-student.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTYlJUjYSkZkXcGOG_r97USZjuFLXz9iU',
    appId: '1:641698702113:ios:2ba123bf35437f76709460',
    messagingSenderId: '641698702113',
    projectId: 'getx-student',
    storageBucket: 'getx-student.appspot.com',
    iosBundleId: 'com.example.myFirstGetxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTYlJUjYSkZkXcGOG_r97USZjuFLXz9iU',
    appId: '1:641698702113:ios:d88d0c22b4f80c8c709460',
    messagingSenderId: '641698702113',
    projectId: 'getx-student',
    storageBucket: 'getx-student.appspot.com',
    iosBundleId: 'com.example.myFirstGetxApp.RunnerTests',
  );
}
